# Generated by Django 5.2.8 on 2025-11-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('IT', 'Information Technology'), ('HR', 'Human Resources'), ('FIN', 'Finance'), ('MKT', 'Marketing'), ('OPS', 'Operations'), ('ENG', 'Engineering'), ('SALES', 'Sales'), ('ADMIN', 'Administration')], max_length=100),
        ),
    ]
